name: bootstop
channels:
  - conda-forge
  - defaults
dependencies:
  - ampl-mp
  - appnope
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - boost-cpp
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - cloudpickle
  - colorama
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - entrypoints
  - executing
  - filelock
  - fonttools
  - freetype
  - gmp
  - gmpy2
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipopt
  - ipykernel
  - ipyparallel
  - ipython
  - jedi
  - jinja2
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcxx
  - libdeflate
  - libedit
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libopenblas
  - libpng
  - libprotobuf
  - libsodium
  - libsqlite
  - libtiff
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - metis
  - mpc
  - mpfr
  - mpmath
  - mumps-include
  - mumps-seq
  - munkres
  - ncurses
  - nest-asyncio
  - networkx
  - nlopt
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pagmo
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pooch
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pygments
  - pygmo
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pyzmq
  - readline
  - requests
  - scipy
  - scotch
  - setuptools
  - six
  - sleef
  - stack_data
  - sympy
  - tbb
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unixodbc
  - urllib3
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
